package:
  name: pyb2d
  version: 0.2.1

source:
  url: https://github.com/pyb2d/pyb2d/archive/refs/tags/0.2.1.tar.gz
  sha256: c89e42984c65e8815d8f0481819f2016720235fd126b79eccbadd68952181c80


build:
  script: python -m pip install pybind11
  cflags: -Wno-implicit-function-declaration

requirements:
  run:
    - numpy

test:
  imports:
    - b2d
    - b2d.framework