package:
  name: pyb2d
  version: 0.1.1

source:
  url: https://github.com/pyb2d/pyb2d/archive/refs/tags/0.1.4.tar.gz
  sha256: b1fa289bfa04daab0e90d9c819d54abe034d0bb500294169092a2d7c545f60ac


build:
  script: python -m pip install pybind11
  cflags: -Wno-implicit-function-declaration

requirements:
  run:
    - numpy

test:
  imports:
    - b2d
    - b2d.framework