package:
  name: pybox2d
  version: 0.1.0

source:
  url: https://github.com/DerThorsten/pybox2d/archive/refs/tags/0.1.0.tar.gz
  sha256: 1607befb78826680f6d06a8347ff56d5865a723807285cfcf49728b439891c6c


build:
  cflags: -Wno-implicit-function-declaration

requirements:
  run:
    - numpy

test:
  imports:
    - pybox2d
    - pybox2d.framework